### ISSUE TITLE
folder run/dex not created when starting the `getting-started`

### ISSUE THREAD

**Issue by rimvanvliet** [cafienne/getting-started#17]
When started the project with docker compose, the only thing that missed was the creation of the `run/dex` folder. 

After creating the folder, it ran out of the box.

**Comment by tpetter** [comment]
Thanks for reporting this @rimvanvliet 
We've tried to reproduce this on an empty environment - no luck, it worked straight away.

As it now works on your end, we will close the issue and kindly let us know if you found a reproduction path.
