### ISSUE TITLE
Incorrect health checks

### ISSUE THREAD

**Issue by tammert** [cafienne/getting-started#18]
https://github.com/cafienne/getting-started/blob/3d9593055b578851aa9528a71dc72e16c4de63d4/docker-compose.yml#L106

The following lines causes the error `wget: invalid option -- 's' Usage: wget [OPTION]... [URL]... Try wget --help for more options.`, which in turn displays the container as **Unhealthy**.

Suggestion:
`test: ["CMD", "curl", "-sS", "-o", "/dev/null", "http://cafienne:2027/api-docs/swagger.json"]` is working great

**Comment by tammert** [comment]
Similar something for https://github.com/cafienne/getting-started/blob/3d9593055b578851aa9528a71dc72e16c4de63d4/docker-compose.yml#L14

`mailcatcher` uses a BusyBox based container image, which does not contain `curl`. I fixed this with the following test:
`test: ["CMD", "wget", "-q", "--spider", "http://mailcatcher:1080"]`

**Comment by olger** [comment]
hi @tammert, thanks for your findings, I'd like to test them on our environments and merge them into the codebase.

Do you mind provide your fixes as a pull request ? (if not, I'll do it but if you like to, you are more than welcome)

**Comment by tammert** [comment]
@olger #19 :)

**Comment by olger** [comment]
Thanks, I'll look into that this week. 
If you need some help using the whole setup and modelling, you van always open a ticket - or - connect via Gitter: https://gitter.im/cafienne/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link
